# Generated by Django 2.2.5 on 2019-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_images'),
        ),
    ]
