# Generated by Django 3.0.7 on 2020-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190929_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_uploads',
            field=models.IntegerField(default=0),
        ),
    ]
