# Generated by Django 3.0.7 on 2020-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=1000)),
                ('user_avatar', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('liked', models.BooleanField()),
                ('unliked', models.BooleanField()),
                ('liked_by', models.CharField(blank=True, max_length=50)),
                ('unliked_by', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadTorrents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_name', models.CharField(max_length=50)),
                ('torrent_description', models.CharField(max_length=250)),
                ('torrent_image', models.ImageField(null=True, upload_to='static/torrent_images/')),
                ('torrent_file', models.FileField(upload_to='static/torrent-files/')),
                ('likes', models.IntegerField(default=False)),
                ('unlikes', models.IntegerField(default=False)),
                ('uploader_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(default=False)),
            ],
        ),
    ]
