# Generated by Django 3.0.7 on 2020-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadtorrents',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='uploadtorrents',
            name='torrent_description',
            field=models.CharField(max_length=500),
        ),
    ]
