# Generated by Django 3.0.7 on 2020-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0002_auto_20200607_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtorrents',
            name='uploader_name',
            field=models.CharField(default='tabish', max_length=50),
        ),
    ]
