# Generated by Django 3.0.7 on 2020-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0003_auto_20200607_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtorrents',
            name='torrent_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/torrent_images/'),
        ),
    ]
