# Generated by Django 3.0.7 on 2020-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0004_auto_20200607_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtorrents',
            name='uploader_name',
            field=models.CharField(blank=True, default='tabish', max_length=50),
        ),
    ]
