# Generated by Django 3.0.7 on 2020-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0005_auto_20200607_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtorrents',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='uploadtorrents',
            name='unlikes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
