# Generated by Django 3.0.7 on 2020-06-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0008_uploadtorrents_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadtorrents',
            old_name='user_id',
            new_name='user',
        ),
    ]
