# Generated by Django 3.0.7 on 2020-06-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0013_auto_20200608_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_id',
        ),
    ]
