# Generated by Django 3.0.7 on 2020-06-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0014_auto_20200608_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
