# Generated by Django 3.0.7 on 2020-06-08 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0015_auto_20200608_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtorrents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
