# Generated by Django 3.0.7 on 2020-06-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0016_uploadtorrents_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadtorrents',
            name='torrent_name',
        ),
    ]
